"""Tests for Mattermost bot integration module."""

from datetime import datetime, timezone
from unittest.mock import MagicMock, patch

import requests

from src.core.config import _parse_config
from src.core.models import Paper
from src.ranking.rerank_llm import RankedPaper
from src.reports.mattermost import create_post, format_summary, send_digest, upload_file

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_paper(
    title="Test Paper", source_url="https://arxiv.org/abs/1234.5678"
):
    return Paper(
        source_id="1234.5678",
        title=title,
        authors=["Author One", "Author Two"],
        abstract="An abstract.",
        categories=["cs.LG"],
        primary_category="cs.LG",
        submitted_date=datetime(2026, 3, 9, tzinfo=timezone.utc),
        source_url=source_url,
        pdf_url="https://arxiv.org/pdf/1234.5678",
        source_type="arxiv_api",
    )


def _make_ranked(
    title="Test Paper",
    score=8,
    summary="A good paper.",
    source_url="https://arxiv.org/abs/1234.5678",
    abstract_takeaway="Key finding.",
):
    return RankedPaper(
        paper=_make_paper(title=title, source_url=source_url),
        relevance_score=score,
        reasoning="Relevant.",
        summary=summary,
        abstract_takeaway=abstract_takeaway,
    )


# ---------------------------------------------------------------------------
# TestFormatSummary
# ---------------------------------------------------------------------------


class TestFormatSummary:
    def test_basic_format(self):
        papers = [
            _make_ranked(title="Alpha Paper", score=9),
            _make_ranked(title="Beta Paper", score=7),
        ]
        stats = {"total_fetched": 50}
        msg = format_summary(papers, stats)

        assert "Research Radar Digest" in msg
        assert "**2 papers**" in msg
        assert "50 fetched" in msg
        assert "Alpha Paper" in msg
        assert "Beta Paper" in msg
        assert "9/10" in msg
        assert "7/10" in msg
        assert "Generated by Research Radar" in msg

    def test_empty_papers(self):
        msg = format_summary([], {"total_fetched": 50})

        assert "**0 papers**" in msg
        assert "No papers met the relevance threshold" in msg

    def test_table_format(self):
        papers = [_make_ranked(score=8)]
        msg = format_summary(papers, {"total_fetched": 10})

        assert "| Score | Paper |" in msg
        assert "|-------|-------|" in msg
        assert "8/10" in msg

    def test_uses_abstract_takeaway(self):
        papers = [_make_ranked(abstract_takeaway="Important finding.")]
        msg = format_summary(papers, {"total_fetched": 10})

        assert "Important finding." in msg

    def test_falls_back_to_summary_first_sentence(self):
        papers = [
            _make_ranked(
                abstract_takeaway="",
                summary="First sentence. Second sentence.",
            )
        ]
        msg = format_summary(papers, {"total_fetched": 10})

        assert "First sentence." in msg
        assert "Second sentence" not in msg

    def test_paper_without_source_url_uses_pdf(self):
        papers = [_make_ranked(source_url="")]
        msg = format_summary(papers, {"total_fetched": 10})

        assert "[Test Paper](https://arxiv.org/pdf/1234.5678)" in msg


# ---------------------------------------------------------------------------
# TestUploadFile
# ---------------------------------------------------------------------------


class TestUploadFile:
    @patch("src.reports.mattermost.requests.post")
    def test_successful_upload(self, mock_post, tmp_path):
        mock_resp = MagicMock()
        mock_resp.ok = True
        mock_resp.json.return_value = {"file_infos": [{"id": "file123"}]}
        mock_post.return_value = mock_resp

        f = tmp_path / "digest.md"
        f.write_text("# Digest")

        result = upload_file(
            "https://mm.example.com", "tok", "ch1", str(f)
        )

        assert result == "file123"
        call_url = mock_post.call_args[0][0]
        assert call_url == "https://mm.example.com/api/v4/files"

    @patch("src.reports.mattermost.requests.post")
    def test_http_error_returns_none(self, mock_post, tmp_path):
        mock_resp = MagicMock()
        mock_resp.raise_for_status.side_effect = requests.HTTPError("403 Forbidden")
        mock_post.return_value = mock_resp

        f = tmp_path / "digest.md"
        f.write_text("# Digest")

        result = upload_file(
            "https://mm.example.com", "tok", "ch1", str(f)
        )
        assert result is None

    @patch("src.reports.mattermost.requests.post")
    def test_connection_error_returns_none(self, mock_post, tmp_path):
        mock_post.side_effect = requests.ConnectionError("refused")

        f = tmp_path / "digest.md"
        f.write_text("# Digest")

        result = upload_file(
            "https://mm.example.com", "tok", "ch1", str(f)
        )
        assert result is None

    @patch("src.reports.mattermost.requests.post")
    def test_strips_trailing_slash(self, mock_post, tmp_path):
        mock_resp = MagicMock()
        mock_resp.ok = True
        mock_resp.json.return_value = {"file_infos": [{"id": "file1"}]}
        mock_post.return_value = mock_resp

        f = tmp_path / "digest.md"
        f.write_text("# Digest")

        upload_file("https://mm.example.com/", "tok", "ch1", str(f))

        call_url = mock_post.call_args[0][0]
        assert "//api" not in call_url
        assert call_url == "https://mm.example.com/api/v4/files"


# ---------------------------------------------------------------------------
# TestCreatePost
# ---------------------------------------------------------------------------


class TestCreatePost:
    @patch("src.reports.mattermost.requests.post")
    def test_successful_post(self, mock_post):
        mock_resp = MagicMock()
        mock_resp.ok = True
        mock_post.return_value = mock_resp

        result = create_post(
            "https://mm.example.com", "tok", "ch1", "hello"
        )

        assert result is True
        body = mock_post.call_args.kwargs.get(
            "json", mock_post.call_args[1].get("json")
        )
        assert body["channel_id"] == "ch1"
        assert body["message"] == "hello"

    @patch("src.reports.mattermost.requests.post")
    def test_post_with_file_ids(self, mock_post):
        mock_resp = MagicMock()
        mock_resp.ok = True
        mock_post.return_value = mock_resp

        create_post(
            "https://mm.example.com",
            "tok",
            "ch1",
            "hello",
            file_ids=["f1"],
        )

        body = mock_post.call_args.kwargs.get(
            "json", mock_post.call_args[1].get("json")
        )
        assert body["file_ids"] == ["f1"]

    @patch("src.reports.mattermost.requests.post")
    def test_http_error_returns_false(self, mock_post):
        mock_resp = MagicMock()
        mock_resp.raise_for_status.side_effect = requests.HTTPError("403 Forbidden")
        mock_post.return_value = mock_resp

        result = create_post(
            "https://mm.example.com", "tok", "ch1", "hello"
        )
        assert result is False

    @patch("src.reports.mattermost.requests.post")
    def test_connection_error_returns_false(self, mock_post):
        mock_post.side_effect = requests.ConnectionError("refused")

        result = create_post(
            "https://mm.example.com", "tok", "ch1", "hello"
        )
        assert result is False


# ---------------------------------------------------------------------------
# TestSendDigest
# ---------------------------------------------------------------------------


class TestSendDigest:
    @patch("src.reports.mattermost.create_post")
    @patch("src.reports.mattermost.upload_file")
    def test_upload_and_post_success(self, mock_upload, mock_create, tmp_path):
        mock_upload.return_value = "file123"
        mock_create.return_value = True

        f = tmp_path / "digest.md"
        f.write_text("# Report")

        result = send_digest(
            "https://mm.example.com", "tok", "ch1", str(f), "summary text",
        )

        assert result is True
        mock_upload.assert_called_once()
        mock_create.assert_called_once()
        _, kwargs = mock_create.call_args
        assert kwargs.get("file_ids") == ["file123"]

    @patch("src.reports.mattermost.create_post")
    @patch("src.reports.mattermost.upload_file")
    def test_upload_fails_posts_summary_only(self, mock_upload, mock_create, tmp_path):
        mock_upload.return_value = None
        mock_create.return_value = True

        f = tmp_path / "digest.md"
        f.write_text("# Report")

        result = send_digest(
            "https://mm.example.com", "tok", "ch1", str(f), "summary text",
        )

        assert result is True
        mock_create.assert_called_once()
        _, kwargs = mock_create.call_args
        assert "file_ids" not in kwargs

    @patch("src.reports.mattermost.create_post")
    @patch("src.reports.mattermost.upload_file")
    def test_post_fails_returns_false(self, mock_upload, mock_create, tmp_path):
        mock_upload.return_value = "file123"
        mock_create.return_value = False

        f = tmp_path / "digest.md"
        f.write_text("# Report")

        result = send_digest(
            "https://mm.example.com", "tok", "ch1", str(f), "summary text",
        )

        assert result is False

    @patch("src.reports.mattermost.create_post")
    @patch("src.reports.mattermost.upload_file")
    def test_nonexistent_file_posts_summary_only(
        self, mock_upload, mock_create
    ):
        mock_create.return_value = True

        result = send_digest(
            "https://mm.example.com",
            "tok",
            "ch1",
            "/tmp/nonexistent_file_12345.md",
            "summary text",
        )

        assert result is True
        mock_upload.assert_not_called()
        mock_create.assert_called_once()


# ---------------------------------------------------------------------------
# TestMattermostConfig
# ---------------------------------------------------------------------------


class TestMattermostConfig:
    def test_config_values_parsed(self):
        raw = {
            "output": {
                "mattermost_url": "https://mm.example.com",
                "mattermost_channel_id": "ch123",
            }
        }
        config = _parse_config(raw)
        assert config.output.mattermost_url == "https://mm.example.com"
        assert config.output.mattermost_channel_id == "ch123"

    def test_env_var_precedence_for_token(self):
        # Token should come from MATTERMOST_TOKEN env var only
        # This tests that the env var is used at runtime (not in config)
        pass  # Token is read at runtime, not in config parsing

    def test_defaults_to_empty(self):
        config = _parse_config({})
        assert config.output.mattermost_url == ""
        assert config.output.mattermost_channel_id == ""
